services:
  app:
    container_name: finki_aoc_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3333
      - APP_KEY=GenericDevKey1234567890123456
      - LOG_LEVEL=debug
    volumes:
      - ./:/app
      - /app/node_modules